import { describe, it, expect } from 'vitest';
import { testFileRule, exampleFileRule, suppressionCommentRule, generatedFileRule, deadCodeRule } from '../../src/triage/rules.js';
import type { TriageContext } from '../../src/triage/types.js';
import type { Finding } from '../../src/sarif/types.js';

function makeFinding(overrides: Partial<Finding> = {}): Finding {
  return {
    ruleId: 'test-rule',
    level: 'warning',
    message: 'test message',
    filePath: 'src/app.ts',
    startLine: 10,
    tool: 'test',
    confidence: 75,
    ...overrides,
  };
}

function makeContext(finding: Finding, source = ''): TriageContext {
  return {
    finding,
    sourceLines: source.split('\n'),
    surroundingLines: 10,
  };
}

describe('testFileRule', () => {
  it('should flag test files as false positive', () => {
    const paths = [
      'src/app.test.ts',
      'src/app.spec.ts',
      'tests/unit/app.ts',
      '__tests__/app.ts',
      'test_app.py',
    ];

    for (const filePath of paths) {
      const finding = makeFinding({ filePath });
      const result = testFileRule.check(makeContext(finding));
      expect(result?.verdict, `expected ${filePath} to be false_positive`).toBe('false_positive');
    }
  });

  it('should flag fixture/mock files', () => {
    const paths = ['fixtures/data.json', 'mocks/api.ts'];
    for (const filePath of paths) {
      const finding = makeFinding({ filePath });
      const result = testFileRule.check(makeContext(finding));
      expect(result?.verdict).toBe('false_positive');
    }
  });

  it('should not flag production files', () => {
    const finding = makeFinding({ filePath: 'src/auth/login.ts' });
    const result = testFileRule.check(makeContext(finding));
    expect(result).toBeNull();
  });
});

describe('exampleFileRule', () => {
  it('should flag example/docs files', () => {
    const paths = [
      'examples/demo.py',
      'docs/api.md',
      'samples/app.ts',
      'demo/index.html',
    ];

    for (const filePath of paths) {
      const finding = makeFinding({ filePath });
      const result = exampleFileRule.check(makeContext(finding));
      expect(result?.verdict, `expected ${filePath} to be false_positive`).toBe('false_positive');
    }
  });

  it('should not flag src files', () => {
    const finding = makeFinding({ filePath: 'src/core/engine.ts' });
    const result = exampleFileRule.check(makeContext(finding));
    expect(result).toBeNull();
  });
});

describe('suppressionCommentRule', () => {
  it('should detect nosemgrep comment', () => {
    const finding = makeFinding({ startLine: 2 });
    const source = 'line1\nsome_code() # nosemgrep\nline3';
    const result = suppressionCommentRule.check(makeContext(finding, source));
    expect(result?.verdict).toBe('false_positive');
  });

  it('should detect noqa comment', () => {
    const finding = makeFinding({ startLine: 1 });
    const source = 'x = dangerous_thing()  # noqa';
    const result = suppressionCommentRule.check(makeContext(finding, source));
    expect(result?.verdict).toBe('false_positive');
  });

  it('should detect eslint-disable on previous line', () => {
    const finding = makeFinding({ startLine: 2 });
    const source = '// eslint-disable-next-line\ndangerousCode();';
    const result = suppressionCommentRule.check(makeContext(finding, source));
    expect(result?.verdict).toBe('false_positive');
  });

  it('should not flag lines without suppression', () => {
    const finding = makeFinding({ startLine: 1 });
    const source = 'normalCode();';
    const result = suppressionCommentRule.check(makeContext(finding, source));
    expect(result).toBeNull();
  });
});

describe('generatedFileRule', () => {
  it('should flag generated files by path', () => {
    const paths = [
      'src/api.generated.ts',
      'dist/bundle.js',
      'build/output.js',
      'vendor/lib.js',
      'package-lock.json',
      'src/types.g.ts',
    ];

    for (const filePath of paths) {
      const finding = makeFinding({ filePath });
      const result = generatedFileRule.check(makeContext(finding));
      expect(result?.verdict, `expected ${filePath} to be false_positive`).toBe('false_positive');
    }
  });

  it('should flag files with generated header', () => {
    const finding = makeFinding({ filePath: 'src/api-client.ts' });
    const source = '// Auto-generated by openapi-codegen\n// Do not edit\nexport class ApiClient {}';
    const result = generatedFileRule.check(makeContext(finding, source));
    expect(result?.verdict).toBe('false_positive');
  });

  it('should not flag normal source files', () => {
    const finding = makeFinding({ filePath: 'src/app.ts' });
    const source = 'import { Router } from "express";\nconst app = Router();';
    const result = generatedFileRule.check(makeContext(finding, source));
    expect(result).toBeNull();
  });
});

describe('deadCodeRule', () => {
  it('should flag commented-out code', () => {
    const finding = makeFinding({ startLine: 1 });
    const sources = [
      '// dangerousFunction()',
      '# insecure_call()',
      '/* vulnerable code */',
    ];

    for (const source of sources) {
      const result = deadCodeRule.check(makeContext(finding, source));
      expect(result?.verdict).toBe('false_positive');
    }
  });

  it('should not flag active code', () => {
    const finding = makeFinding({ startLine: 1 });
    const source = 'dangerousFunction();';
    const result = deadCodeRule.check(makeContext(finding, source));
    expect(result).toBeNull();
  });
});
