import type { TriageRule, TriageContext, TriageRuleResult } from './types.js';

export const testFileRule: TriageRule = {
  name: 'test-file',
  check(context: TriageContext): TriageRuleResult | null {
    const path = context.finding.filePath.toLowerCase();
    const testPatterns = [
      /\.test\./,
      /\.spec\./,
      /_test\./,
      /(^|\/)tests?\//,
      /(^|\/)test_/,
      /(^|\/)?__tests__\//,
      /(^|\/)fixtures?\//,
      /(^|\/)mocks?\//,
    ];

    if (testPatterns.some(p => p.test(path))) {
      return {
        verdict: 'false_positive',
        reason: 'Finding is in a test/fixture file',
        confidence: 95,
      };
    }
    return null;
  },
};

export const exampleFileRule: TriageRule = {
  name: 'example-file',
  check(context: TriageContext): TriageRuleResult | null {
    const path = context.finding.filePath.toLowerCase();
    const patterns = [
      /(^|\/)examples?\//,
      /(^|\/)docs?\//,
      /(^|\/)documentation\//,
      /(^|\/)samples?\//,
      /(^|\/)demo\//,
      /\.example\./,
      /\.sample\./,
    ];

    if (patterns.some(p => p.test(path))) {
      return {
        verdict: 'false_positive',
        reason: 'Finding is in example/documentation code',
        confidence: 85,
      };
    }
    return null;
  },
};

export const suppressionCommentRule: TriageRule = {
  name: 'suppression-comment',
  check(context: TriageContext): TriageRuleResult | null {
    const { finding, sourceLines } = context;
    const lineIdx = finding.startLine - 1;

    if (lineIdx < 0 || lineIdx >= sourceLines.length) return null;

    const line = sourceLines[lineIdx];
    const prevLine = lineIdx > 0 ? sourceLines[lineIdx - 1] : '';

    const suppressionPatterns = [
      /nosemgrep/,
      /noqa/,
      /nolint/,
      /NOLINT/,
      /eslint-disable/,
      /prettier-ignore/,
      /type:\s*ignore/,
      /@suppress/,
    ];

    if (suppressionPatterns.some(p => p.test(line) || p.test(prevLine))) {
      return {
        verdict: 'false_positive',
        reason: 'Finding has suppression comment (already acknowledged)',
        confidence: 90,
      };
    }
    return null;
  },
};

export const generatedFileRule: TriageRule = {
  name: 'generated-file',
  check(context: TriageContext): TriageRuleResult | null {
    const path = context.finding.filePath.toLowerCase();
    const generatedPatterns = [
      /\.generated\./,
      /\.auto\./,
      /\.g\./,
      /(^|\/)generated\//,
      /(^|\/)gen\//,
      /\.min\./,
      /\.bundle\./,
      /(^|\/)dist\//,
      /(^|\/)build\//,
      /(^|\/)vendor\//,
      /(^|\/)node_modules\//,
      /\.lock$/,
      /lock\.json$/,
    ];

    if (generatedPatterns.some(p => p.test(path))) {
      return {
        verdict: 'false_positive',
        reason: 'Finding is in generated/vendored code',
        confidence: 90,
      };
    }

    // Check first few lines for "generated" markers
    const header = context.sourceLines.slice(0, 5).join('\n').toLowerCase();
    if (
      header.includes('auto-generated') ||
      header.includes('do not edit') ||
      header.includes('generated by') ||
      header.includes('this file is generated')
    ) {
      return {
        verdict: 'false_positive',
        reason: 'File header indicates generated code',
        confidence: 85,
      };
    }

    return null;
  },
};

export const deadCodeRule: TriageRule = {
  name: 'dead-code',
  check(context: TriageContext): TriageRuleResult | null {
    const { finding, sourceLines } = context;
    const lineIdx = finding.startLine - 1;

    if (lineIdx < 0 || lineIdx >= sourceLines.length) return null;

    const line = sourceLines[lineIdx].trim();

    // Check if line is commented out
    if (
      line.startsWith('//') ||
      line.startsWith('#') ||
      line.startsWith('/*') ||
      line.startsWith('*')
    ) {
      return {
        verdict: 'false_positive',
        reason: 'Finding is on a commented-out line',
        confidence: 90,
      };
    }

    return null;
  },
};

export const inputValidationRule: TriageRule = {
  name: 'input-validated',
  check(context: TriageContext): TriageRuleResult | null {
    const { finding, sourceLines } = context;
    const lineIdx = finding.startLine - 1;

    if (lineIdx < 0 || lineIdx >= sourceLines.length) return null;

    // Check 20 lines before the finding for sanitization/validation patterns
    const lookback = 20;
    const start = Math.max(0, lineIdx - lookback);
    const precedingCode = sourceLines.slice(start, lineIdx).join('\n').toLowerCase();

    const validationPatterns = [
      // Sanitization functions
      /sanitize[_a-z]*\s*\(/,
      /escape[_a-z]*\s*\(/,
      /encode[_a-z]*\s*\(/,
      /clean[_a-z]*\s*\(/,
      /strip[_a-z]*\s*\(/,
      /purify\s*\(/,
      /htmlspecialchars\s*\(/,
      /dompurify/,
      // Validation checks
      /validate[_a-z]*\s*\(/,
      /isvalid[_a-z]*\s*\(/,
      /is_valid[_a-z]*\s*\(/,
      /check[_a-z]*\s*\(/,
      /verify[_a-z]*\s*\(/,
      // Type coercion / parsing (safe conversion)
      /parseint\s*\(/,
      /parsefloat\s*\(/,
      /number\s*\(/,
      /int\s*\(/,
      /float\s*\(/,
      // Schema validation
      /\.parse\s*\(/,
      /\.safeParse\s*\(/,
      /zod/,
      /joi\./,
      /yup\./,
      /ajv/,
      // Parameterized queries (SQL)
      /\?\s*,/,
      /\$\d+/,
      /%s/,
      /placeholder/,
      // ORM usage (usually safe)
      /\.where\s*\(\s*\{/,
      /\.findone\s*\(/,
      /\.findmany\s*\(/,
      /\.create\s*\(\s*\{/,
      /prisma\./,
      /sequelize\./,
      /typeorm/,
    ];

    if (validationPatterns.some(p => p.test(precedingCode))) {
      return {
        verdict: 'false_positive',
        reason: 'Input appears sanitized/validated upstream (within 20 lines)',
        confidence: 70,
      };
    }

    return null;
  },
};

export const unreachableCodeRule: TriageRule = {
  name: 'unreachable-code',
  check(context: TriageContext): TriageRuleResult | null {
    const { finding, sourceLines } = context;
    const lineIdx = finding.startLine - 1;

    if (lineIdx < 0 || lineIdx >= sourceLines.length) return null;

    // Check if the finding is inside a block that's gated by a constant false condition
    const lookback = 10;
    const start = Math.max(0, lineIdx - lookback);
    const precedingLines = sourceLines.slice(start, lineIdx);

    for (const line of precedingLines) {
      const trimmed = line.trim().toLowerCase();

      // Feature flag / constant false guards
      if (
        /if\s*\(\s*false\s*\)/.test(trimmed) ||
        /if\s*\(\s*0\s*\)/.test(trimmed) ||
        /if\s+false\s*:/.test(trimmed) ||
        /if\s*\(\s*!?\s*enabled\s*\)/.test(trimmed) ||
        /if\s*\(\s*process\.env\./.test(trimmed) && /===?\s*['"]/.test(trimmed)
      ) {
        return {
          verdict: 'uncertain',
          reason: 'Finding may be behind a feature flag or conditional guard',
          confidence: 50,
        };
      }

      // Early return / throw before the finding
      if (
        /^\s*(return|throw|process\.exit|sys\.exit)\b/.test(line) &&
        !/^\s*(\/\/|#|\/\*|\*)/.test(line) // not a comment
      ) {
        // Check if return is at same or higher indentation level
        const returnIndent = line.search(/\S/);
        const findingIndent = sourceLines[lineIdx].search(/\S/);
        if (returnIndent <= findingIndent) {
          return {
            verdict: 'false_positive',
            reason: 'Unreachable: early return/throw before finding at same scope level',
            confidence: 75,
          };
        }
      }
    }

    return null;
  },
};

export const defaultTriageRules: TriageRule[] = [
  testFileRule,
  exampleFileRule,
  suppressionCommentRule,
  generatedFileRule,
  deadCodeRule,
  inputValidationRule,
  unreachableCodeRule,
];
