import type { TriageRule, TriageContext, TriageRuleResult } from './types.js';

export const testFileRule: TriageRule = {
  name: 'test-file',
  check(context: TriageContext): TriageRuleResult | null {
    const path = context.finding.filePath.toLowerCase();
    const testPatterns = [
      /\.test\./,
      /\.spec\./,
      /_test\./,
      /(^|\/)tests?\//,
      /(^|\/)test_/,
      /(^|\/)?__tests__\//,
      /(^|\/)fixtures?\//,
      /(^|\/)mocks?\//,
    ];

    if (testPatterns.some(p => p.test(path))) {
      return {
        verdict: 'false_positive',
        reason: 'Finding is in a test/fixture file',
        confidence: 95,
      };
    }
    return null;
  },
};

export const exampleFileRule: TriageRule = {
  name: 'example-file',
  check(context: TriageContext): TriageRuleResult | null {
    const path = context.finding.filePath.toLowerCase();
    const patterns = [
      /(^|\/)examples?\//,
      /(^|\/)docs?\//,
      /(^|\/)documentation\//,
      /(^|\/)samples?\//,
      /(^|\/)demo\//,
      /\.example\./,
      /\.sample\./,
    ];

    if (patterns.some(p => p.test(path))) {
      return {
        verdict: 'false_positive',
        reason: 'Finding is in example/documentation code',
        confidence: 85,
      };
    }
    return null;
  },
};

export const suppressionCommentRule: TriageRule = {
  name: 'suppression-comment',
  check(context: TriageContext): TriageRuleResult | null {
    const { finding, sourceLines } = context;
    const lineIdx = finding.startLine - 1;

    if (lineIdx < 0 || lineIdx >= sourceLines.length) return null;

    const line = sourceLines[lineIdx];
    const prevLine = lineIdx > 0 ? sourceLines[lineIdx - 1] : '';

    const suppressionPatterns = [
      /nosemgrep/,
      /noqa/,
      /nolint/,
      /NOLINT/,
      /eslint-disable/,
      /prettier-ignore/,
      /type:\s*ignore/,
      /@suppress/,
    ];

    if (suppressionPatterns.some(p => p.test(line) || p.test(prevLine))) {
      return {
        verdict: 'false_positive',
        reason: 'Finding has suppression comment (already acknowledged)',
        confidence: 90,
      };
    }
    return null;
  },
};

export const generatedFileRule: TriageRule = {
  name: 'generated-file',
  check(context: TriageContext): TriageRuleResult | null {
    const path = context.finding.filePath.toLowerCase();
    const generatedPatterns = [
      /\.generated\./,
      /\.auto\./,
      /\.g\./,
      /(^|\/)generated\//,
      /(^|\/)gen\//,
      /\.min\./,
      /\.bundle\./,
      /(^|\/)dist\//,
      /(^|\/)build\//,
      /(^|\/)vendor\//,
      /(^|\/)node_modules\//,
      /\.lock$/,
      /lock\.json$/,
    ];

    if (generatedPatterns.some(p => p.test(path))) {
      return {
        verdict: 'false_positive',
        reason: 'Finding is in generated/vendored code',
        confidence: 90,
      };
    }

    // Check first few lines for "generated" markers
    const header = context.sourceLines.slice(0, 5).join('\n').toLowerCase();
    if (
      header.includes('auto-generated') ||
      header.includes('do not edit') ||
      header.includes('generated by') ||
      header.includes('this file is generated')
    ) {
      return {
        verdict: 'false_positive',
        reason: 'File header indicates generated code',
        confidence: 85,
      };
    }

    return null;
  },
};

export const deadCodeRule: TriageRule = {
  name: 'dead-code',
  check(context: TriageContext): TriageRuleResult | null {
    const { finding, sourceLines } = context;
    const lineIdx = finding.startLine - 1;

    if (lineIdx < 0 || lineIdx >= sourceLines.length) return null;

    const line = sourceLines[lineIdx].trim();

    // Check if line is commented out
    if (
      line.startsWith('//') ||
      line.startsWith('#') ||
      line.startsWith('/*') ||
      line.startsWith('*')
    ) {
      return {
        verdict: 'false_positive',
        reason: 'Finding is on a commented-out line',
        confidence: 90,
      };
    }

    return null;
  },
};

export const defaultTriageRules: TriageRule[] = [
  testFileRule,
  exampleFileRule,
  suppressionCommentRule,
  generatedFileRule,
  deadCodeRule,
];
